# Generated by Django 4.1.5 on 2023-01-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
